### ISSUE TITLE
Lacking lib.split_genomes_mash

### ISSUE THREAD

**Issue by deandz2** [Alexamk/decRiPPter#1]
Hi Alexamk,

I installed the program and the run was not successful due to the lack of lib.split_genomes_mash on lib folder. I could not find this python module even when installing mash onto the environment.

Would you mind providing the modules or showing me how I can obtain it? Thanks.

**Comment by Alexamk** [comment]
Hello,

No need. That script was removed from the pipeline, I just forgot to remove the import line.
It is now fixed in the latest version.
Thanks, Alex
