### ISSUE TITLE
UnboundLocalError: local variable 'operon' referenced before assignment

### ISSUE THREAD

**Issue by NZ-HIPS** [Alexamk/decRiPPter#2]
getting this error while trying to mine some genomes from the NCBI with gene_cluster_formation.py

Traceback (most recent call last):
  File "./gene_cluster_formation.py", line 1137, in <module>
    genome_collections = make_collections_per_genomes(operons,genome_dict)
  File "./gene_cluster_formation.py", line 523, in make_collections_per_genomes
    collection_type='genome',realname=genome.descr,active=True)
  File "/home/asf/decRiPPter/lib/Genes.py", line 455, in __init__
    self.prep()
  File "/home/asf/decRiPPter/lib/Genes.py", line 471, in prep
    self.set_flanks()
  File "/home/asf/decRiPPter/lib/Genes.py", line 492, in set_flanks
    operon.right_flank = None
UnboundLocalError: local variable 'operon' referenced before assignment

**Comment by Alexamk** [comment]
Hello,
I've added a new branch (hotfix_operons), that should hopefully resolve the issue. Please try to run the code onto that branch and let me know if it works.

**Comment by nlouwen** [comment]
It does resolve the issue, but generates two runtime warnings. I expect due to line 63 of lib/write_html.py. Here, np.average and np.std are used on an empty list, which returns nan.

```
..Python\lib\site-packages\numpy\lib\function_base.py:393: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
..Python\lib\site-packages\numpy\core\_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

..Python\lib\site-packages\numpy\core\_methods.py:216: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
..Python\lib\site-packages\numpy\core\_methods.py:185: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
..Python\lib\site-packages\numpy\core\_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

Output as example:
![afbeelding](https://user-images.githubusercontent.com/94065538/141486191-e69b5963-d1d3-40c5-8fcc-8d77c51bf18b.png)

**Comment by Alexamk** [comment]
I see. Looks like these errors occur because there are genomes in the dataset that don't contain any hits. I'll look into it in more detail in a bit.

**Comment by Alexamk** [comment]
I've added a small fix for this on the same branch. It should work fine now. The reason it's giving NaN is because the collection is empty (after filtering). But it will no longer give a Numpy warning for it.
Can you check if it is working well now?

**Comment by nlouwen** [comment]
Yes, it works perfectly now.

**Comment by Alexamk** [comment]
Integrated the fixes into master
