### ISSUE TITLE
TypeError Sequence Item 0

### ISSUE THREAD

**Issue by asweezy00** [Alexamk/decRiPPter#4]
Hello, 
The following error occurred when python genecluster_formation -o path/to/output PROJECT_NAME was used. 

Traceback (most recent call last):
   File "gene_cluster_formation.py",line 1121, in <module>
precursor_group_names,precursor_operon_collections,ops,original_paris_prec,sp,sg -  group_precursors.main(operons,mibig_domaindict,settings)
File "/home/lab/software/decRiPPter/lib/group_operons_precursors.py",
  muscle_operator(operon_collections,path,settings['cores'])
File "home/lab/software/decRiPPTer/lib_groups_operons_precursors.py", line 193, in muscle_operator
  out_text= ' ',join(results)
TypeError: sequence item 0: expected string,exceptions.ValueError found

**Comment by Alexamk** [comment]
Hello,
It looks like running MUSCLE is causing the issue. Please confirm that it is installed (open a command line terminal in the environment where you run decRiPPter, and try to run it).
If the issue still persists, please run the script again with maximum verbosity (-v 3), and upload the logfile you get in the results folder.

**Comment by asweezy00** [comment]
The issue is resolved and I can generate output.html however when I try to use a larger dataset such as 800 complete genomes it gives me the following error during the genome prep stage 

Traceback (most recent call last):
  File "genome_prep.py", line 720, in <module>
    genome_seqs, gene_names, scaf_names, files_parsed = prep_parse_operator(genomes_annotated, settings, genome_seqs_prod, gene_names_prod, scaf_names_prod, files_parsed_prod)
  File "genome_prep.py", line 130, in prep_parse_operator
    results = operator(genomes_annotated, cores, prep_parse_worker, worker_args)
  File "/home/lab/software/decRiPPter/lib/multiprocessing_wrappers.py", line 60, in operator
    raise res
ValueError: Process id 427 ran into an error:
Traceback (most recent call last):
  File "/home/lab/software/decRiPPter/lib/multiprocessing_wrappers.py", line 114, in worker_wrapper
    result = function(*job_args)
  File "genome_prep.py", line 164, in prep_parse_worker
    name = feat.qualifers['product'][0]
AttributeError: 'SeqFeature' object has no attribute 'qualifers'

**Comment by Alexamk** [comment]
That seems to be related not so much to the size of your database, but to one of your gbk files.
This could be due to the way decRiPPter parses, or due to a strange gbk file format. 
Can you run it with max. verbosity (-v 3) and see which file is giving the problem?

**Comment by asweezy00** [comment]
I saw and deleted the files with the problems it runs fine now. I have a lot of files and split them in groups and then run them. Is there a benefit to using the program with as many files as possible at a time? Does a larger dataset give better results?

**Comment by Alexamk** [comment]
All right, good to hear. If it's possible, can you share one or more of the files that caused issues? I just want to see if it is fixable.

If you compare more genomes, the COG-scores should be more accurate. But beyond a certain amount this won't affect much (around 50 genomes in my experience, although I haven't tested it with many different genera).
Also, all the gene clusters in a single dataset are compared with each other to find putative gene cluster families, so running more at the same time might find families that would otherwise be missed
